name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
      - main
      - track/**

jobs:
  integration-tests:
    uses: ./.github/workflows/integration_test.yaml
    secrets: inherit
  publish-to-edge:
    needs: [integration-tests]
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    secrets: inherit
    with:
      trivy-image-config: "trivy.yaml"
      integration-test-provider: microk8s
      integration-test-provider-channel: 1.25-strict/stable
      integration-test-juju-channel: 3.1/stable
      integration-test-modules: '["test_charm"]'
